#!/usr/bin/env python3
"""
Generate a Tier 2-only Wix CMS import CSV for the Toolkits collection.

Source of truth: the toolkit HTMLs in templates/documents/ (structure + content)
and the pairing rules in toolkit_dataset.md. channel-pricing is EXCLUDED (already
live in Wix). The 3 Tier 1 rows are EXCLUDED (separate file).

Column order matches toolkits_csv_for_wix_import.csv so the import auto-maps to
the live field Keys. The `Image`/preview field is intentionally NOT a column
(media cannot be CSV-imported; select the *_preview.png in Wix Media per row).

Placeholders to resolve after import:
  - pdf_url: upload the named PDF to Wix Media, paste the public URL.
  - second_toolkit_pdf_url: live for channel-pricing + pbm-compensation; others upload.
  - field_note_*: Option A (2026-05-29) routes Email 3 to the always-live Contract
    Language Library for every row, so Email 3 never dead-links to an unpublished
    Field Note. Each row's drafted dedicated field-note title/blurb is kept in the
    data below (fn_title / fn_blurb) and swapped into that row as the Field Note ships.

Run: python3 email_gated_toolkit/build_tier2_csv.py
"""

import csv
import os

COLUMNS = [
    "slug", "Title", "eyebrow", "headline", "headline_emphasis", "subtitle",
    "bullet_1", "bullet_2", "bullet_3", "bullet_4",
    "valueprop_card_1_title", "valueprop_card_1_body",
    "valueprop_card_2_title", "valueprop_card_2_body",
    "valueprop_card_3_title", "valueprop_card_3_body",
    "valueprop_card_4_title", "valueprop_card_4_body",
    "pdf_filename_display", "seo_title", "seo_description",
    "related_toolkit_slugs", "image_alt_text", "pdf_url", "tier",
    "mechanic_phrase", "is_featured", "is_archived",
    "second_toolkit_name", "second_toolkit_pdf_url", "second_toolkit_blurb",
    "field_note_title", "field_note_blurb", "field_note_url",
]

# Live Wix Media URLs already known
URL_CHANNEL = "https://f4a10ae5-926c-402e-bec1-e9ae8845f739.usrfiles.com/ugd/f4a10a_23fa36ae1b824651a117a6ed99437003.pdf"
URL_PBMCOMP = "https://f4a10ae5-926c-402e-bec1-e9ae8845f739.usrfiles.com/ugd/f4a10a_bb76ebca1b994c0db20e64985f6a5b44.pdf"

def up(fname):
    return f"[Upload {fname} to Wix Media, paste URL]"

# Email 3 default destination (Option A, chosen 2026-05-29): until each toolkit's
# dedicated Field Note publishes, Email 3 routes to the always-live evergreen
# Contract Language Library so it never dead-links. Each row's drafted dedicated
# field-note title/blurb is preserved below in `fn_title`/`fn_blurb` and swapped in
# per row as that Field Note ships.
LIBRARY_URL = "https://benefitblindspots.substack.com/p/pbm-contract-language-library"
LIBRARY_TITLE = "The PBM Contract Language Library"
LIBRARY_BLURB = ("Free and evergreen: the protective PBM contract language behind this "
                 "audit, with the exact redlines to ask your PBM for. Drawn from the "
                 "patterns we see across hundreds of contract reviews a year.")

SUBTITLE = ("A 2-page printable {kind} PBS uses across 100s of PBM contract reviews "
            "annually. Free download. Sent to your inbox.")

def seo_desc(kind, line):
    return f"{line} {kind.capitalize()} PBS uses across 100s of PBM contract reviews annually. Free download."

# Each row: only the fields that vary. Helpers fill the rest.
ROWS = [
    dict(
        slug="pa-roi-audit", Title="PA ROI Audit Scorecard", kind="scorecard",
        eyebrow="TIER 2 · PRIOR AUTHORIZATION · ROI AUDIT SCORECARD",
        headline="Your PA Program Has a Cost. Few Plans Measure It.",
        headline_emphasis="The Five-Metric Scorecard to Audit PA ROI.",
        bullets=["Five-metric PA ROI rubric to score your program",
                 "Approval rate, turnaround, appeal-overturn, admin load, member abandonment",
                 "Traffic-light scoring: where PA adds value vs. friction",
                 "Optimization plan for the metrics scoring red"],
        cards=[("Score the Five Metrics", "Run your PA program against the five-metric rubric: approval rate, turnaround time, appeal-overturn rate, administrative load, and member abandonment. Each scores green, yellow, or red."),
               ("Find the Friction", "A high appeal-overturn rate means the PA was denying care it should have approved. A high abandonment rate means members gave up at the counter. Both are PA doing harm, not control."),
               ("Separate Value from Theater", "Some PA saves real money on genuinely misused drugs. Some is administrative theater that delays therapy and generates appeals. The scorecard tells them apart."),
               ("This Quarter's Action Plan", "Score the program, flag the red metrics, and bring the documented friction points to your PBM. Require turnaround-time and overturn-rate reporting in the next contract cycle.")],
        mechanic="prior authorization ROI", pillar="Clinical Pharmacy Perspectives",
        alt="Prior authorization ROI scorecard with traffic-light scoring on five program metrics",
        pdf=up("week_16_pa_roi_audit_scorecard.pdf"),
        related="step-therapy-override, quarterly-reporting, pbm-disclosure-audit",
        second_name="Step Therapy Override Audit", second_url=up("week_26_thursday_step_therapy_override_audit.pdf"),
        second_blurb="Prior authorization and step therapy are two halves of the same utilization-management lever. The Step Therapy Override Audit checks whether the override workflow your contract promises actually runs when a member needs it.",
        fn_title="PA Turnaround Time: What Your Contract Should Guarantee",
        fn_blurb="The scorecard surfaces where PA adds friction. This Field Note covers the contract language that caps turnaround time and forces the overturn-rate reporting most plans never see."),

    dict(
        slug="carve-out-decision", Title="Carve-Out Decision Scorecard", kind="scorecard",
        eyebrow="TIER 2 · PHARMACY CARVE-OUT · DECISION SCORECARD",
        headline="Carve Out the Pharmacy Benefit. Or Don't.",
        headline_emphasis="The 10-Factor Scorecard Behind the Decision.",
        bullets=["10-factor carve-out vs. bundled evaluation rubric",
                 "Score transparency, rebate flow, data access, and switching cost",
                 "Weighted result points to carve-out or stay-bundled",
                 "Decision-ready summary for the benefits committee"],
        cards=[("Score the Ten Factors", "Evaluate the carve-out decision across ten factors: pricing transparency, rebate pass-through, data access, clinical control, network flexibility, switching cost, and more. Each scored against your current bundled arrangement."),
               ("Weight What Matters", "Not every factor weighs the same for every plan. The scorecard lets you weight transparency and rebate flow heavier when those are your live pain points, so the result reflects your priorities."),
               ("Read the Recommendation", "A high score favors carving the pharmacy benefit out to a transparent PBM. A low score means your bundled arrangement is serving you, or the switching cost outweighs the gain this cycle."),
               ("This Quarter's Action Plan", "Score the ten factors, document the rationale, and bring the weighted recommendation to your benefits committee. If carve-out wins, the RFP Scoring Audit is the next step.")],
        mechanic="carve-out vs bundled", pillar="Self-Funded Employer Guidance",
        alt="Ten-factor carve-out decision scorecard comparing bundled versus carved-out pharmacy benefit",
        pdf=up("week_17_carve_out_decision_scorecard.pdf"),
        related="rfp-scoring-audit, pbm-compensation, optimize-vs-go-to-market",
        second_name="RFP Scoring Methodology Audit", second_url=up("week_25_thursday_rfp_scoring_audit_worksheet.pdf"),
        second_blurb="If the carve-out decision points to going to market, the RFP Scoring Methodology Audit is what comes next. It checks the scoring weights before the RFP goes out, so the methodology favors your plan and not the incumbent.",
        fn_title="The First 90 Days After Carve-Out",
        fn_blurb="The scorecard makes the decision. This Field Note covers the operational reality of the switch: data migration, member communication, and the transition pitfalls that catch most plans by surprise."),

    dict(
        slug="drug-pipeline-watch", Title="Drug Pipeline Watch List 2026-2027", kind="reference card",
        eyebrow="TIER 2 · DRUG PIPELINE · 2026-2027 WATCH LIST",
        headline="Five Drug Categories Will Hit Your Plan.",
        headline_emphasis="The 18-Month Pipeline Watch List.",
        bullets=["Five drug categories most likely to move pharmacy spend",
                 "Cost framing and plan-impact summary per category",
                 "4-item prep checklist for each category",
                 "Quarterly pipeline review process + four PBM questions"],
        cards=[("Know the Five Categories", "The watch list tracks the five drug categories most likely to affect pharmacy spend over the next 18 months, each with a cost framing and a plain-language plan-impact summary."),
               ("Prep Before the Launch", "Each category carries a 4-item prep checklist. Budgeting and utilization-management decisions made before a high-cost launch beat scrambling after the claims arrive."),
               ("Build the Quarterly Review", "Page 2 lays out a quarterly pipeline review process so the watch list becomes a standing cadence, not a one-time read. Pipeline awareness is a renewal-negotiation asset."),
               ("This Quarter's Action Plan", "Review the five categories, run the prep checklist on the ones relevant to your population, and put the four PBM pipeline questions on your next quarterly-review agenda.")],
        mechanic="pipeline cost exposure", pillar="Cost Containment Strategies",
        alt="Drug pipeline watch list reference card with five drug categories and cost-impact framing",
        pdf=up("week_18_drug_pipeline_watch_list.pdf"),
        related="biosimilar-readiness, copay-card-calculator, h1-renewal-readiness",
        second_name="Biosimilar Readiness Assessment", second_url=up("week_22_biosimilar_readiness_assessment.pdf"),
        second_blurb="Biosimilars are one of the highest-leverage pipeline categories. The Biosimilar Readiness Assessment scores whether your plan is positioned to capture the savings as the next wave of biosimilars launches.",
        fn_title="One Drug Class to Watch Next",
        fn_blurb="The watch list is the 18-month view. This Field Note zooms into the single category most likely to surprise plan budgets next, and what to ask your PBM now."),

    dict(
        slug="fiduciary-documentation", Title="Fiduciary Documentation Checklist", kind="checklist",
        eyebrow="TIER 2 · ERISA FIDUCIARY · DOCUMENTATION CHECKLIST",
        headline="Courts Don't Judge Outcomes. They Judge Process.",
        headline_emphasis="The Five-Category Fiduciary Documentation Checklist.",
        bullets=["Five documentation categories courts evaluate for prudent process",
                 "Required records and a 'what good looks like' framing per category",
                 "The One-Page Test: five core documents every plan should hold",
                 "4-step audit workflow to close documentation gaps"],
        cards=[("Audit Five Categories", "ERISA judges process, not results. The checklist covers the five documentation categories courts evaluate when assessing a prudent pharmacy-benefit process, with the required records for each."),
               ("Know What Good Looks Like", "Each category includes a 'what good looks like' framing, so you can tell a defensible file from a thin one before a regulator or a plaintiff's attorney does."),
               ("Run the One-Page Test", "Five core documents decide whether your fiduciary file holds up. If you can't produce all five today, that gap is itself the finding."),
               ("This Quarter's Action Plan", "Run the five-category audit, take the One-Page Test, and use the 4-step workflow to close the gaps. Fiduciary documentation is cheap insurance against a problem that is very expensive without it.")],
        mechanic="fiduciary documentation", pillar="Self-Funded Employer Guidance",
        alt="Fiduciary documentation checklist with five ERISA categories and a one-page test",
        pdf=up("week_19_fiduciary_documentation_checklist.pdf"),
        related="fiduciary-compliance-audit, pbm-disclosure-audit, pre-meeting-renewal-checklist",
        second_name="Fiduciary Compliance Audit", second_url=up("week_32_thursday_fiduciary_compliance_audit.pdf"),
        second_blurb="The Documentation Checklist builds the file. The Fiduciary Compliance Audit pressure-tests it against the ERISA standard a court actually applies, and documents the co-fiduciary defense that protects the individuals on the committee.",
        fn_title="What ERISA Actually Requires of a Pharmacy Plan Fiduciary",
        fn_blurb="The checklist builds the file. This Field Note explains the legal standard behind it: what 'prudent process' means in practice and why documentation, not outcome, is what survives a challenge."),

    dict(
        slug="copay-card-calculator", Title="Copay Card Financial Impact Calculator", kind="walkthrough",
        eyebrow="TIER 2 · COPAY CARDS · FINANCIAL IMPACT CALCULATOR",
        headline="Manufacturer Copay Cards Shift Cost. The Plan Absorbs It.",
        headline_emphasis="The Five-Step Calculator to Model the Shift.",
        bullets=["Five-step model of the cost shift from copay cards to the plan",
                 "Accumulator vs. maximizer decision matrix",
                 "Where the copay-card value actually lands, and with whom",
                 "Implementation worksheet for the option you choose"],
        cards=[("Model the Cost Shift", "Walk the five-step calculation to model how manufacturer copay-card dollars shift cost onto the plan, and how much of that value the PBM captures through an accumulator program."),
               ("Compare Accumulator vs. Maximizer", "The decision matrix lays out copay accumulator against copay maximizer: how each treats the manufacturer's assistance, the member's deductible, and the plan's net cost."),
               ("Find Where the Value Lands", "The calculator makes visible who actually keeps the copay-card value: the member, the plan, or the PBM. On most contracts it is not the member, and not the plan."),
               ("This Quarter's Action Plan", "Run the five-step model on your highest-cost copay-card drugs, choose accumulator or maximizer with eyes open, and use the implementation worksheet to put the decision into the contract.")],
        mechanic="copay card cost shift", pillar="Cost Containment Strategies",
        alt="Copay card financial impact calculator with accumulator versus maximizer decision matrix",
        pdf=up("week_20_copay_card_financial_impact_calculator.pdf"),
        related="cob-audit, pbm-compensation, drug-pipeline-watch",
        second_name="Coordination of Benefits Audit Worksheet", second_url=up("week_30_thursday_cob_audit_worksheet.pdf"),
        second_blurb="Copay-program economics live inside the coordination-of-benefits clause. The COB Audit Worksheet checks how a single claim coordinates across programs, which is where accumulator and maximizer value is quietly captured or returned.",
        fn_title="Copay Accumulators: The Program Running in Your Plan",
        fn_blurb="The calculator models the dollars. This Field Note explains the accumulator program itself: how it routes the manufacturer's assistance away from your member's deductible and back toward the PBM."),

    dict(
        slug="rebate-report-audit", Title="Rebate Report Audit Worksheet", kind="worksheet",
        eyebrow="TIER 2 · REBATE REPORT · AUDIT WORKSHEET",
        headline="Your PBM Reports 100% Pass-Through. Audit the Noun.",
        headline_emphasis="The Audit Worksheet to Reconcile the Rebate Report.",
        bullets=["Three audit passes on the rebate report your PBM sends",
                 "Reconcile 'received' rebates against manufacturer-paid rebates",
                 "Where a rebate aggregator's cut hides before pass-through",
                 "Paste-ready broker request for the missing detail"],
        cards=[("Pull the Rebate Detail", "Open your most recent rebate report. Pull rebate-per-claim and total rebate by drug. The summary number is designed to reassure; the per-drug detail is where the reconciliation happens."),
               ("Reconcile Received vs. Paid", "'100% pass-through' usually means 100% of what the PBM received, not what the manufacturer paid. If a rebate aggregator took a cut first, the two numbers differ, and only one is on your report."),
               ("Audit the Definitions", "Check how the contract defines 'rebate.' A narrow definition leaves market-share payments, admin allowances, and price-protection rebates outside the pass-through clause entirely."),
               ("This Quarter's Action Plan", "Run the three passes, document the gap between received and paid, and send the paste-ready request for aggregator-level detail to your broker before the next quarterly review.")],
        mechanic="rebate reconciliation", pillar="Transparency & Industry Education",
        alt="Rebate report audit worksheet reconciling received versus manufacturer-paid rebates",
        pdf=up("week_20_thursday_rebate_report_audit_worksheet.pdf"),
        related="pbm-compensation, channel-pricing, quarterly-reporting",
        second_name="PBM Compensation Audit Worksheet", second_url=URL_PBMCOMP,
        second_blurb="Rebate retention is one of five revenue streams that flow from your plan to your PBM. The PBM Compensation Audit Worksheet maps all five, so you can see how the rebate cut fits the larger compensation picture.",
        fn_title="Reading the Rebate Report Without Getting Spun",
        fn_blurb="The worksheet reconciles the numbers. This Field Note walks the language: the words in the rebate report and the contract that let a middleman sit between what the manufacturer paid and what your plan receives."),

    dict(
        slug="quarterly-reporting", Title="Quarterly Reporting Checklist", kind="checklist",
        eyebrow="TIER 2 · PBM QUARTERLY REPORT · AUDIT CHECKLIST",
        headline="Your PBM's Quarterly Report Is Built to Reassure.",
        headline_emphasis="The 15-Line Checklist for What It Should Contain.",
        bullets=["15 line items a complete PBM quarterly report should contain",
                 "Check your most recent report against the full list",
                 "Paste-ready broker request for the missing lines",
                 "4-step quarterly action plan"],
        cards=[("Check the 15 Line Items", "A complete quarterly report contains 15 specific line items: total spend, generic dispensing rate, mail-order penetration, specialty trend, rebate per claim, and more. Check your most recent report against the full list."),
               ("Find What's Missing", "Whatever line item is missing is missing for a reason. Aggregate summaries hide the trend lines that predict your renewal. The gaps are where the negotiation leverage lives."),
               ("Request the Detail", "The checklist includes paste-ready broker request language for the lines your PBM left off. Most reporting gaps close simply because you asked in writing."),
               ("This Quarter's Action Plan", "Run the 15-line check, request the missing detail, and build the cadence: every quarter, the same checklist against the new report. Patterns surface across quarters that a single report hides.")],
        mechanic="quarterly report completeness", pillar="PBM Contract Insights",
        alt="Quarterly reporting checklist with fifteen line items a complete PBM report should contain",
        pdf=up("week_21_quarterly_reporting_checklist.pdf"),
        related="midyear-claims-red-flag, pbm-disclosure-audit, pbm-compensation",
        second_name="PBM Disclosure Audit Worksheet", second_url=up("week_31_thursday_pbm_disclosure_audit.pdf"),
        second_blurb="The quarterly report is what the PBM volunteers. The PBM Disclosure Audit Worksheet covers what the PBM owes you annually whether it volunteers it or not, and tracks which disclosures you actually received.",
        fn_title="Five Lines to Read First in Your PBM's Quarterly Report",
        fn_blurb="The checklist is the full 15-line audit. This is the 30-minute version: the five lines to scan in the most recent quarterly report this week, and what each one is hiding when it's missing."),

    dict(
        slug="biosimilar-readiness", Title="Biosimilar Readiness Assessment", kind="scorecard",
        eyebrow="TIER 2 · BIOSIMILARS · READINESS ASSESSMENT",
        headline="The Biosimilar Savings Are Real. Most Plans Miss Them.",
        headline_emphasis="The Six-Factor Biosimilar Readiness Assessment.",
        bullets=["Six-factor Strong/Moderate/Weak biosimilar readiness rubric",
                 "Formulary placement, interchangeability, and incentive alignment",
                 "Where the PBM's rebate on the reference brand blocks the switch",
                 "Readiness gaps mapped to fixes"],
        cards=[("Score Six Factors", "Assess your plan's biosimilar readiness across six factors using a Strong / Moderate / Weak rubric: formulary placement, interchangeability handling, provider adoption, member incentives, and rebate-conflict exposure."),
               ("Find the Rebate Conflict", "The most common reason a plan misses biosimilar savings: the PBM earns a larger rebate on the high-priced reference brand, so its formulary quietly keeps the brand preferred over cheaper biosimilars."),
               ("Map Gaps to Fixes", "Each Weak score points to a specific fix, whether that's a formulary change, an interchangeability policy, or a contract term that aligns the PBM's incentive with your savings."),
               ("This Quarter's Action Plan", "Score the six factors, flag the Weak ones, and require your PBM to show biosimilar uptake and the rebate differential on the reference brand. The savings are there; readiness is what captures them.")],
        mechanic="biosimilar savings capture", pillar="Clinical Pharmacy Perspectives",
        alt="Biosimilar readiness assessment scorecard with a six-factor strong-moderate-weak rubric",
        pdf=up("week_22_biosimilar_readiness_assessment.pdf"),
        related="specialty-routing, drug-pipeline-watch, pbm-compensation",
        second_name="Specialty Routing Audit Worksheet", second_url=up("week_22_thursday_specialty_routing_audit_worksheet.pdf"),
        second_blurb="Biosimilars are specialty drugs, and where they fill decides the price. The Specialty Routing Audit Worksheet checks the five clauses that determine whether your specialty scripts route to a competitive pharmacy or the PBM's own.",
        fn_title="The Biosimilar Opportunity Your Plan Is Missing",
        fn_blurb="The assessment scores readiness. This Field Note explains the mechanism behind the miss: how a rebate on the reference brand keeps a more expensive drug preferred over the biosimilar that would save your plan money."),

    dict(
        slug="specialty-routing", Title="Specialty Routing Audit Worksheet", kind="worksheet",
        eyebrow="TIER 2 · SPECIALTY ROUTING · AUDIT WORKSHEET",
        headline="Five Clauses Decide Where Your Specialty Drugs Fill.",
        headline_emphasis="The PBM Owns Four. The Audit Worksheet Surfaces Them.",
        bullets=["Three audit passes on specialty routing",
                 "Five clauses that decide where specialty scripts fill",
                 "Quantify concentration in the PBM's own specialty pharmacy",
                 "Paste-ready broker request to open the network"],
        cards=[("Pull the Routing Data", "Sort your specialty claims by filling pharmacy. The first pass quantifies how much of your specialty spend runs through the PBM's own specialty pharmacy versus everywhere else."),
               ("Read the Five Clauses", "Five contract clauses decide specialty routing: the network definition, the prior-auth pathway, the exclusive-distribution terms, the white-bagging policy, and the site-of-care rules. The PBM wrote most of them."),
               ("Match Pattern to Clause", "Compare the actual routing pattern to what the clauses permit. A concentration far above the network definition is a steering finding, and a renewal-leverage item."),
               ("This Quarter's Action Plan", "Run the three passes, document the owned-pharmacy concentration, and send the paste-ready request to open competitive specialty dispensing before your next renewal.")],
        mechanic="specialty routing concentration", pillar="Clinical Pharmacy Perspectives",
        alt="Specialty routing audit worksheet with five contract clauses and a routing concentration pattern",
        pdf=up("week_22_thursday_specialty_routing_audit_worksheet.pdf"),
        related="network-configuration-audit, channel-pricing, pbm-compensation",
        second_name="Pharmacy Network Configuration Audit", second_url=up("week_29_thursday_network_configuration_audit.pdf"),
        second_blurb="Specialty routing is one slice of where members fill. The Network Configuration Audit zooms out to the whole network design and the exclusion log, where the same steering pattern shows up across retail and mail.",
        fn_title="White Bagging, Brown Bagging, and Where Your Specialty Dollars Go",
        fn_blurb="The worksheet quantifies the concentration. This Field Note decodes the routing vocabulary, white bagging and site-of-care steering, and how the contract turns a clinical decision into a margin decision."),

    dict(
        slug="midyear-claims-red-flag", Title="Mid-Year Claims Red Flag Checklist", kind="checklist",
        eyebrow="TIER 2 · MID-YEAR CLAIMS · RED FLAG CHECKLIST",
        headline="Your Renewal Is Being Decided by June's Claims.",
        headline_emphasis="The Five-Pattern Mid-Year Red Flag Checklist.",
        bullets=["Five claims-data patterns that predict renewal trajectory",
                 "The data-pull request to run at the H1 mark",
                 "Intervention pathway for each pattern",
                 "Renewal-prep action per red flag"],
        cards=[("Pull the Mid-Year Data", "At the H1 mark, pull the claims data the checklist specifies. The patterns that will define your renewal are already in the PBM's system; the question is whether you see them before the PBM presents terms."),
               ("Scan Five Patterns", "Five claims patterns predict renewal trajectory: specialty concentration shifts, generic-efficiency erosion, rebate-per-claim drift, high-cost-claimant emergence, and mail-order migration. Each is a flag the summary report hides."),
               ("Intervene Before Renewal", "Each pattern carries an intervention pathway. Caught at mid-year, a drifting trend has months to correct. Caught at renewal, it is already an outcome the PBM is pricing against you."),
               ("This Quarter's Action Plan", "Run the data pull, score the five patterns, and act on the red flags now. Walking into renewal with documented mid-year findings flips the leverage back to the plan sponsor.")],
        mechanic="mid-year claims patterns", pillar="Cost Containment Strategies",
        alt="Mid-year claims red flag checklist with five claims-data patterns that predict renewal",
        pdf=up("week_23_midyear_claims_red_flag_checklist.pdf"),
        related="h1-renewal-readiness, quarterly-reporting, pbr-framework",
        second_name="H1 Renewal Readiness Scorecard", second_url=up("week_24_h1_renewal_readiness_scorecard.pdf"),
        second_blurb="The red flags tell you what's drifting. The H1 Renewal Readiness Scorecard turns those patterns into a renewal-leverage score on the same five metrics the PBM already models into its proposal.",
        fn_title="The Mid-Year Data Window Most Plans Never Use",
        fn_blurb="The checklist names the five patterns. This Field Note makes the timing case: why the employer who analyzes at mid-year has months of leverage, and the one who waits has weeks."),

    dict(
        slug="h1-renewal-readiness", Title="H1 Renewal Readiness Scorecard", kind="scorecard",
        eyebrow="TIER 2 · H1 RENEWAL · READINESS SCORECARD",
        headline="Your PBM Already Modeled Your Renewal. Score It First.",
        headline_emphasis="The Five-Metric H1 Renewal Readiness Scorecard.",
        bullets=["Score renewal leverage on the five metrics PBMs model",
                 "GER, PMPM trend, specialty %, rebate per brand claim, high-cost claimants",
                 "See your position before the PBM presents its proposal",
                 "Convert the score into a renewal agenda"],
        cards=[("Score Five Metrics", "Score your renewal readiness on the five metrics PBMs already build into their proposals: generic effective rate, PMPM trend, specialty percentage, rebate per brand claim, and high-cost-claimant count."),
               ("See What the PBM Sees", "The PBM walks into renewal having modeled all five. The scorecard puts the same five in front of you first, so you are reading from the same sheet rather than reacting to theirs."),
               ("Find the Leverage", "A weak score on one metric is a negotiation target, not just a problem. The scorecard turns each metric into a documented ask for the renewal table."),
               ("This Quarter's Action Plan", "Score the five metrics at the H1 mark, build the renewal agenda from the weak ones, and pre-circulate the findings to your committee before the first PBM renewal meeting.")],
        mechanic="H1 renewal leverage", pillar="Self-Funded Employer Guidance",
        alt="H1 renewal readiness scorecard scoring five metrics PBMs model into renewal proposals",
        pdf=up("week_24_h1_renewal_readiness_scorecard.pdf"),
        related="pre-meeting-renewal-checklist, midyear-claims-red-flag, midyear-guarantee-audit",
        second_name="First Renewal Meeting Pre-Meeting Checklist", second_url=up("week_37_thursday_pre_meeting_renewal_checklist.pdf"),
        second_blurb="The scorecard builds your renewal position. The Pre-Meeting Checklist makes sure you walk into the first renewal meeting with the five documents and the counter-narrative that set the frame before the PBM does.",
        fn_title="Five Numbers That Determine Your Renewal Leverage",
        fn_blurb="The scorecard scores the five metrics. This Field Note explains why these five, and how each one moves the renewal proposal the PBM hands you in the fall."),

    dict(
        slug="contract-amendment-letter", Title="Mid-Year Contract Amendment Letter Template", kind="template",
        eyebrow="TIER 2 · MID-YEAR AMENDMENT · LETTER TEMPLATE",
        headline="Five Clauses Govern Mid-Year Amendments.",
        headline_emphasis="Most Plan Sponsors Never Invoke Them. The Template Does.",
        bullets=["Three steps to a mid-year amendment letter",
                 "Five clauses that govern when and how you can amend",
                 "Paste your audit findings into the redline letter",
                 "Ninety-day notice window, used on your timeline"],
        cards=[("Know the Five Clauses", "Five contract clauses govern mid-year amendments: the amendment-rights clause, the notice window, the remediation terms, the guarantee true-up, and the termination-for-cause trigger. Most plan sponsors never invoke any of them."),
               ("Build the Letter in Three Steps", "The template walks three steps: document the finding, cite the governing clause, and state the requested amendment with a deadline. Paste your audit findings straight into the redline."),
               ("Use the Notice Window", "The 90-day notice window is leverage when you start it, not when the PBM does. A mid-year amendment letter beats waiting for year-end, when the renewal cycle reabsorbs every open item."),
               ("This Quarter's Action Plan", "Pull your audit findings, map each to its governing clause, send the amendment letter inside the notice window, and track the PBM's response against the remediation terms.")],
        mechanic="mid-year amendment", pillar="PBM Contract Insights",
        alt="Mid-year amendment letter template with five governing clauses and a redline request",
        pdf=up("week_24_thursday_contract_amendment_letter.pdf"),
        related="midyear-guarantee-audit, termination-clause-audit, optimize-vs-go-to-market",
        second_name="Mid-Year Performance Guarantee Audit", second_url=up("week_34_thursday_midyear_guarantee_audit.pdf"),
        second_blurb="The amendment letter is the action. The Mid-Year Performance Guarantee Audit is what generates the findings that fill it: the guarantees you should check at mid-year, before year-end notification makes remediation impossible.",
        fn_title="What a PBM Transition Actually Looks Like: Timeline and Pitfalls",
        fn_blurb="Amend or exit is the decision. This Field Note covers the operational reality of the exit path: six months minimum from notice to go-live, and the pitfalls that catch most plans by surprise."),

    dict(
        slug="rfp-scoring-audit", Title="RFP Scoring Methodology Audit", kind="worksheet",
        eyebrow="TIER 2 · PBM RFP · SCORING METHODOLOGY AUDIT",
        headline="Five RFP Scoring Terms Decide the Winner.",
        headline_emphasis="The PBM Knows Your Methodology. The Audit Fixes It First.",
        bullets=["Three audit passes on your RFP scoring methodology",
                 "Five scoring terms that decide which PBM wins",
                 "Where the weights quietly favor the incumbent",
                 "Adjust the methodology before the RFP goes out"],
        cards=[("Audit the Scoring Weights", "The first pass examines how your RFP allocates points: price, transparency, clinical programs, service, and implementation. The weights decide the winner before a single response arrives."),
               ("Find the Incumbent Advantage", "Incumbent PBMs know how your methodology scores because they have seen it before. The audit surfaces where the weights quietly favor the status quo over a more transparent challenger."),
               ("Read the Five Terms", "Five scoring terms decide the outcome: how price is normalized, how rebate guarantees are credited, how definitions are compared, how service is weighted, and how disruption is scored."),
               ("This Quarter's Action Plan", "Run the three passes, rebalance the weights to reward transparency and auditability, and lock the methodology before the RFP goes out. The scoring sheet is the negotiation, made early.")],
        mechanic="RFP scoring methodology", pillar="Broker/Consultant Resources",
        alt="RFP scoring methodology audit worksheet with five scoring terms and weighting analysis",
        pdf=up("week_25_thursday_rfp_scoring_audit_worksheet.pdf"),
        related="termination-clause-audit, carve-out-decision, definition-variance-audit",
        second_name="Termination Clause Audit Worksheet", second_url=up("week_35_thursday_termination_clause_audit.pdf"),
        second_blurb="An RFP only has teeth if you can actually leave. The Termination Clause Audit checks the five terms that decide your exit leverage, so the new contract you sign is one you can also walk away from.",
        fn_title="What I'd Ask Every PBM in an RFP",
        fn_blurb="The audit fixes the scoring. This Field Note is the question set: the RFP questions that separate a transparent PBM from one that scores well on paper and keeps the spread anyway."),

    dict(
        slug="step-therapy-override", Title="Step Therapy Override Audit", kind="worksheet",
        eyebrow="TIER 2 · STEP THERAPY OVERRIDE · AUDIT WORKSHEET",
        headline="Five Clauses Govern Step Therapy Overrides.",
        headline_emphasis="The Workflow Rarely Matches the Clause.",
        bullets=["Three audit passes on step therapy overrides",
                 "Five clauses that govern when an override must be granted",
                 "Where the operational workflow fails the contract",
                 "Member-impact log to document the gap"],
        cards=[("Read the Override Clauses", "Five clauses govern step therapy overrides: the medical-exception standard, the turnaround requirement, the grandfathering terms, the continuity-of-care rule, and the appeal pathway. The contract promises an override process."),
               ("Test the Workflow", "The promise and the practice diverge. The second pass tests whether the override workflow actually runs in the turnaround the contract requires, or whether members abandon therapy waiting."),
               ("Document Member Impact", "Pull the override and abandonment data. A pattern of slow or denied overrides on clinically appropriate exceptions is both a member-harm finding and a contract-compliance finding."),
               ("This Quarter's Action Plan", "Run the three passes, document where the workflow fails the clause, and require override turnaround reporting. Step therapy that can't be overridden on time is cost control doing clinical harm.")],
        mechanic="step therapy overrides", pillar="Clinical Pharmacy Perspectives",
        alt="Step therapy override audit worksheet with five governing clauses and a workflow test",
        pdf=up("week_26_thursday_step_therapy_override_audit.pdf"),
        related="pa-roi-audit, member-transition-audit, quarterly-reporting",
        second_name="PA ROI Audit Scorecard", second_url=up("week_16_pa_roi_audit_scorecard.pdf"),
        second_blurb="Step therapy and prior authorization are the two halves of utilization management. The PA ROI Audit Scorecard scores whether the broader PA program is adding value or just friction, on the same five-metric rubric.",
        fn_title="When Step Therapy Becomes a Barrier, Not a Bridge",
        fn_blurb="The worksheet audits the override workflow. This Field Note covers the clinical cost of getting it wrong: members stable on a therapy forced to fail a cheaper drug first, and the contract language that prevents it."),

    dict(
        slug="pbm-compensation", Title="PBM Compensation Audit Worksheet", kind="worksheet",
        eyebrow="TIER 2 · PBM COMPENSATION · AUDIT WORKSHEET",
        headline="Five Revenue Streams Flow from Your Plan to Your PBM.",
        headline_emphasis="Most Plan Sponsors Track One. The Worksheet Maps All Five.",
        bullets=["Three audit passes across five compensation mechanisms",
                 "Spread, rebate retention, admin fees, owned-pharmacy margin, manufacturer fees",
                 "The comprehensive view single-stream audits miss",
                 "One contract, five places the money moves"],
        cards=[("Map Five Revenue Streams", "Your PBM earns from your plan five ways: pricing spread, retained rebates, administrative fees, margin on its owned pharmacies, and manufacturer-paid fees. Most plan sponsors track only one."),
               ("Audit Each Mechanism", "Three passes walk each stream: what the contract permits, what the report discloses, and what an independent audit would find. The gaps between the three are the compensation hiding in plain sight."),
               ("See the Whole Picture", "Single-mechanic audits (channel pricing, rebate, GER) each surface one stream. This worksheet is the zoom-out that totals all five into one compensation number you can take to renewal."),
               ("This Quarter's Action Plan", "Run the five-stream audit, total the documented compensation, and require disclosure of every stream in the next contract. You cannot negotiate a number you have never been allowed to see.")],
        mechanic="PBM compensation streams", pillar="Transparency & Industry Education",
        alt="PBM compensation audit worksheet mapping five revenue streams from plan to PBM",
        pdf=URL_PBMCOMP,
        related="quarterly-reporting, channel-pricing, rebate-report-audit",
        second_name="Quarterly Reporting Checklist", second_url=up("week_21_quarterly_reporting_checklist.pdf"),
        second_blurb="The Compensation Worksheet maps what to look for. The Quarterly Reporting Checklist audits whether the PBM is actually showing it: the 15 line items a complete report contains, and the broker request for the ones it leaves off.",
        fn_title="The Five Ways Your PBM Gets Paid",
        fn_blurb="The worksheet maps all five streams. This Field Note tells the story behind them: how a benefit manager became a five-stream revenue business, and why tracking only the spread misses most of the money."),

    dict(
        slug="ger-audit", Title="Generic Effective Rate Audit Worksheet", kind="worksheet",
        eyebrow="TIER 2 · GENERIC EFFECTIVE RATE · AUDIT WORKSHEET",
        headline="Five GER Terms Decide Whether Your Guarantee Applies.",
        headline_emphasis="The PBM Controls Four. The Worksheet Checks All Five.",
        bullets=["Three audit passes on your generic effective rate guarantee",
                 "Five GER terms that decide whether the guarantee applies",
                 "Reconcile the guaranteed rate against actual performance",
                 "Where exclusions quietly shrink the guarantee"],
        cards=[("Read the Five GER Terms", "Five terms decide whether your GER guarantee means anything: the generic definition, the included-claims set, the reconciliation method, the exclusion list, and the true-up timing. The PBM controls four of them."),
               ("Reconcile Guaranteed vs. Actual", "Pull your generic effective rate and compare the guaranteed number to actual performance. A guarantee hit on paper while your plan overpays in practice is the GER game working as designed."),
               ("Find the Exclusions", "GER guarantees are met by what they exclude. Single-source generics, specialty generics, and reclassified drugs carved out of the calculation are where the guaranteed average and your real cost diverge."),
               ("This Quarter's Action Plan", "Run the three passes, reconcile guaranteed against actual, and require the exclusion list and reconciliation method in writing. A GER guarantee you cannot audit is a number, not a guarantee.")],
        mechanic="generic effective rate", pillar="PBM Contract Insights",
        alt="Generic effective rate audit worksheet with five GER terms and a reconciliation",
        pdf=up("week_28_thursday_ger_audit_worksheet.pdf"),
        related="channel-pricing, definition-variance-audit, pbm-compensation",
        second_name="Channel Pricing Audit Worksheet", second_url=URL_CHANNEL,
        second_blurb="GER and channel pricing are the two financial audits that surface the most spread. The Channel Pricing Audit Worksheet checks per-channel net cost, where the same reclassification game shows up across retail, mail, and specialty.",
        fn_title="The Generic Guarantee That Doesn't Guarantee Much",
        fn_blurb="The worksheet reconciles the rate. This Field Note decodes the GER mechanism: how a guaranteed average is hit through exclusions and reclassification while your plan's actual generic cost runs higher."),

    dict(
        slug="network-configuration-audit", Title="Pharmacy Network Configuration Audit", kind="worksheet",
        eyebrow="TIER 2 · PHARMACY NETWORK · CONFIGURATION AUDIT",
        headline="Five Network Terms Set Where Members Fill.",
        headline_emphasis="The Routing Pattern Rarely Matches the Clause.",
        bullets=["Three audit passes on your pharmacy network design",
                 "Five terms that set where members are allowed to fill",
                 "Compare the routing pattern to the exclusion log",
                 "Where 'preferred network' becomes a funnel"],
        cards=[("Read the Five Network Terms", "Five terms set your network: the preferred-pharmacy definition, the exclusion criteria, the mail-order mandate, the specialty carve-out, and the out-of-network penalty. Together they decide where members are allowed to fill."),
               ("Compare Pattern to Design", "Pull where claims actually fill and compare it to the network the contract describes. A routing pattern concentrated in PBM-owned pharmacies beyond what the design requires is a steering finding."),
               ("Audit the Exclusion Log", "Which pharmacies got excluded, and why? An exclusion log that quietly removes independent and competing pharmacies turns a 'preferred network' into a funnel toward the PBM's own."),
               ("This Quarter's Action Plan", "Run the three passes, document the routing-versus-design gap, and require the exclusion rationale in writing. A network you did not design is a network designed for someone else's margin.")],
        mechanic="network configuration", pillar="PBM Contract Insights",
        alt="Pharmacy network configuration audit worksheet with five network terms and an exclusion log",
        pdf=up("week_29_thursday_network_configuration_audit.pdf"),
        related="specialty-routing, channel-pricing, cob-audit",
        second_name="Specialty Routing Audit Worksheet", second_url=up("week_22_thursday_specialty_routing_audit_worksheet.pdf"),
        second_blurb="Network design and specialty routing are the same steering question at two scales. The Specialty Routing Audit zooms into the highest-cost slice, where the five routing clauses send your specialty scripts to the PBM's own pharmacy.",
        fn_title="Your Pharmacy Network Was Designed. Just Not by You.",
        fn_blurb="The worksheet audits the design. This Field Note explains how preferred-network and exclusion terms quietly route members and dollars, and how to read the network clause for the funnel inside it."),

    dict(
        slug="cob-audit", Title="Coordination of Benefits Audit Worksheet", kind="worksheet",
        eyebrow="TIER 2 · COORDINATION OF BENEFITS · AUDIT WORKSHEET",
        headline="Five COB Terms Decide How a Single Claim Coordinates.",
        headline_emphasis="The Flag Is Rarely Audited. The Worksheet Checks It.",
        bullets=["Three audit passes on coordination of benefits",
                 "Five COB terms that decide how a claim coordinates",
                 "Where copay-program economics actually live",
                 "The COB flag most plans never check"],
        cards=[("Read the Five COB Terms", "Five terms govern coordination of benefits: the primary-payer rule, the carve-out coordination, the copay-program treatment, the secondary-claim logic, and the recovery clause. Each decides how a single claim splits."),
               ("Find the Copay-Program Money", "Coordination of benefits is where copay-card and accumulator economics actually live. How a claim coordinates decides whether the manufacturer's assistance benefits the member, the plan, or the PBM."),
               ("Audit the COB Flag", "The COB flag on a claim is rarely audited, which is exactly why it matters. The third pass checks whether coordination is running the way the contract describes or quietly favoring the PBM's recovery."),
               ("This Quarter's Action Plan", "Run the three passes, trace how a sample of coordinated claims actually split, and require COB reporting. The clause nobody audits is the clause worth auditing.")],
        mechanic="coordination of benefits", pillar="PBM Contract Insights",
        alt="Coordination of benefits audit worksheet with five COB terms and a claim-coordination trace",
        pdf=up("week_30_thursday_cob_audit_worksheet.pdf"),
        related="copay-card-calculator, network-configuration-audit, pbm-disclosure-audit",
        second_name="Copay Card Financial Impact Calculator", second_url=up("week_20_copay_card_financial_impact_calculator.pdf"),
        second_blurb="COB is where copay-program value is captured or returned. The Copay Card Financial Impact Calculator models the dollars: how much manufacturer assistance shifts to the plan, and how accumulator versus maximizer changes who keeps it.",
        fn_title="The Claim Coordination Nobody Audits",
        fn_blurb="The worksheet traces the coordination. This Field Note explains why COB is where copay-program economics hide, and how a rarely-checked flag decides who keeps the manufacturer's assistance."),

    dict(
        slug="pbm-disclosure-audit", Title="PBM Disclosure Audit Worksheet", kind="worksheet",
        eyebrow="TIER 2 · PBM DISCLOSURE · AUDIT WORKSHEET",
        headline="Five Disclosures Your PBM Owes You Annually.",
        headline_emphasis="Most Plan Sponsors Receive One. The Worksheet Tracks All Five.",
        bullets=["Three audit passes on your PBM's disclosure obligations",
                 "Five disclosures the PBM owes you annually",
                 "Track what you received against what's owed",
                 "Paste-ready inquiry record for the missing disclosures"],
        cards=[("Know the Five Disclosures", "Your PBM owes you five disclosures annually: direct and indirect compensation, rebate aggregation, owned-affiliate transactions, formulary-decision rationale, and conflict-of-interest reporting. Most plan sponsors receive one, if any."),
               ("Track Received vs. Owed", "The worksheet tracks what you actually received against what the contract and law require. A disclosure you never got is not a missing email; it is a compliance gap with your name on it."),
               ("Build the Inquiry Record", "For each missing disclosure, the worksheet generates a paste-ready inquiry. The written request creates the record, and the record is what protects the fiduciary if the disclosure never comes."),
               ("This Quarter's Action Plan", "Run the three passes, document the disclosure gaps, send the inquiries, and require all five in the next contract. Disclosure you have to ask for repeatedly is disclosure designed not to happen.")],
        mechanic="PBM disclosure obligations", pillar="Transparency & Industry Education",
        alt="PBM disclosure audit worksheet tracking five annual disclosures received versus owed",
        pdf=up("week_31_thursday_pbm_disclosure_audit.pdf"),
        related="fiduciary-documentation, quarterly-reporting, pbm-compensation",
        second_name="Fiduciary Documentation Checklist", second_url=up("week_19_fiduciary_documentation_checklist.pdf"),
        second_blurb="The disclosures you collect feed the fiduciary file. The Fiduciary Documentation Checklist organizes them into the five-category record courts evaluate, so the disclosures you chased down actually protect you.",
        fn_title="What Your PBM Is Required to Tell You, and Won't Unless You Ask",
        fn_blurb="The worksheet tracks the five disclosures. This Field Note explains the obligations behind them: what the contract and ERISA require the PBM to disclose, and why the asking is on you."),

    dict(
        slug="fiduciary-compliance-audit", Title="Fiduciary Compliance Audit", kind="worksheet",
        eyebrow="TIER 2 · ERISA FIDUCIARY · COMPLIANCE AUDIT",
        headline="ERISA's Five Words Define Your Personal Exposure.",
        headline_emphasis="The Documentation Is What Survives the Audit.",
        bullets=["Three audit passes against the ERISA prudence standard",
                 "How the five-word duty maps to pharmacy-benefit decisions",
                 "The decision log that documents prudent process",
                 "The co-fiduciary defense for the committee"],
        cards=[("Apply the ERISA Standard", "ERISA's duty turns on a few words: acting prudently, solely in the interest of participants. The audit maps that standard onto the pharmacy-benefit decisions your committee actually makes."),
               ("Build the Decision Log", "Prudence is proven by process, not outcome. The audit builds the decision log that shows how each material pharmacy-benefit choice was made, on what information, and with what advice."),
               ("Document the Co-Fiduciary Defense", "Personal exposure is real. The third pass documents the co-fiduciary defense: the records that protect the individuals on the committee when the process is later questioned."),
               ("This Quarter's Action Plan", "Run the three passes, build the decision log, and close the documentation gaps. The pharmacy benefit is a fiduciary act whether the committee treats it as one or not.")],
        mechanic="fiduciary compliance", pillar="Self-Funded Employer Guidance",
        alt="Fiduciary compliance audit worksheet applying the ERISA prudence standard with a decision log",
        pdf=up("week_32_thursday_fiduciary_compliance_audit.pdf"),
        related="fiduciary-documentation, pbm-disclosure-audit, pre-meeting-renewal-checklist",
        second_name="Fiduciary Documentation Checklist", second_url=up("week_19_fiduciary_documentation_checklist.pdf"),
        second_blurb="The Compliance Audit applies the standard; the Documentation Checklist builds the file it relies on. Run together, they cover both halves: the process you follow and the records that prove you followed it.",
        fn_title="The Pharmacy Benefit Is a Fiduciary Decision. Most Committees Don't Treat It Like One.",
        fn_blurb="The audit applies the ERISA standard. This Field Note makes the case for why pharmacy-benefit oversight is fiduciary work, and what personal exposure looks like when the documentation isn't there."),

    dict(
        slug="member-transition-audit", Title="Member Transition Audit", kind="worksheet",
        eyebrow="TIER 2 · MEMBER TRANSITION · AUDIT WORKSHEET",
        headline="Five Clauses Protect Members During Transitions.",
        headline_emphasis="Most Plan Sponsors Assume They Execute. They Don't.",
        bullets=["Three audit passes on member-transition protection",
                 "Five clauses that protect members during a PBM change",
                 "Transition-event log to test the assumption",
                 "Where continuity-of-care quietly fails"],
        cards=[("Read the Five Protections", "Five clauses protect members through a transition: continuity-of-care, prior-auth honoring, refill-too-soon override, formulary grandfathering, and member-communication timing. Plan sponsors assume they execute automatically."),
               ("Test the Assumption", "They often don't. The second pass builds a transition-event log and checks whether each protection actually fired during the last PBM change or open enrollment, or whether members fell through."),
               ("Document the Gaps", "A member who couldn't refill a maintenance drug during a transition is a contract-execution failure and a member-harm event. The audit documents both, with the clause each gap violated."),
               ("This Quarter's Action Plan", "Run the three passes, log the transition events, and require the PBM to report transition-protection execution. Continuity of care that lives only in the contract is not continuity of care.")],
        mechanic="member transition protection", pillar="PBM Contract Insights",
        alt="Member transition audit worksheet with five protective clauses and a transition-event log",
        pdf=up("week_33_thursday_member_transition_audit.pdf"),
        related="termination-clause-audit, step-therapy-override, h1-renewal-readiness",
        second_name="Termination Clause Audit Worksheet", second_url=up("week_35_thursday_termination_clause_audit.pdf"),
        second_blurb="Member transitions happen when you leave a PBM, which is governed by the termination clause. The Termination Clause Audit checks whether you can exit cleanly, so the transition protections you audited here actually have time to work.",
        fn_title="What Breaks When Members Move Between PBMs",
        fn_blurb="The worksheet tests the protections. This Field Note covers what actually goes wrong in a transition: the maintenance drug that won't refill, the prior-auth that doesn't carry over, and the contract terms that prevent it."),

    dict(
        slug="midyear-guarantee-audit", Title="Mid-Year Performance Guarantee Audit", kind="worksheet",
        eyebrow="TIER 2 · PERFORMANCE GUARANTEES · MID-YEAR AUDIT",
        headline="Five Guarantees You Should Audit at Mid-Year.",
        headline_emphasis="Year-End Notification Comes Too Late.",
        bullets=["Three audit passes on your performance guarantees",
                 "Five guarantees to check at the mid-year mark",
                 "Mid-year notification beats year-end remediation",
                 "Where a guarantee is met on paper but missed in practice"],
        cards=[("Check Five Guarantees", "Five performance guarantees are worth a mid-year check: pricing, rebate, service-level, clinical-program, and reporting guarantees. Each has a measurable mid-year read if you pull the data."),
               ("Audit at Mid-Year", "The PBM notifies you of a missed guarantee at year-end, when the remediation window is closing. A mid-year audit gives you months to invoke the remediation terms instead of weeks."),
               ("Separate Paper from Practice", "A guarantee met on the PBM's summary while your plan's actual experience misses it is the most common finding. The audit reconciles the reported number against your real data."),
               ("This Quarter's Action Plan", "Run the three passes at mid-year, document any guarantee tracking behind target, and send the amendment letter inside the notice window. Year-end is too late to do anything but accept the credit they offer.")],
        mechanic="mid-year guarantee tracking", pillar="PBM Contract Insights",
        alt="Mid-year performance guarantee audit worksheet checking five guarantees against actual data",
        pdf=up("week_34_thursday_midyear_guarantee_audit.pdf"),
        related="contract-amendment-letter, h1-renewal-readiness, ger-audit",
        second_name="Mid-Year Contract Amendment Letter Template", second_url=up("week_24_thursday_contract_amendment_letter.pdf"),
        second_blurb="The Guarantee Audit generates the finding; the Amendment Letter Template acts on it. Paste a tracking-behind-target guarantee into the redline letter and invoke the remediation terms while the notice window is still open.",
        fn_title="Don't Wait for the Year-End Guarantee Reconciliation",
        fn_blurb="The worksheet audits the guarantees at mid-year. This Field Note explains why the timing matters: how year-end notification quietly forecloses the remediation the contract promised."),

    dict(
        slug="termination-clause-audit", Title="Termination Clause Audit", kind="worksheet",
        eyebrow="TIER 2 · TERMINATION CLAUSE · AUDIT WORKSHEET",
        headline="Five Termination Terms Decide Your Leverage.",
        headline_emphasis="Most Plans Are Locked In Without Knowing It.",
        bullets=["Three audit passes on your termination clause",
                 "Five terms that decide whether you can leave clean",
                 "Data ownership, runout pricing, and notice windows",
                 "Build the exit timeline before you need it"],
        cards=[("Read the Five Terms", "Five terms decide your exit leverage: the notice window, the termination-for-cause triggers, the claims-data ownership, the runout-claim pricing, and the transition-assistance obligation. Most plans never read them until they want out."),
               ("Find the Lock-In", "Auto-renewal plus a long notice window plus PBM-owned claims data equals a plan locked in without knowing it. The audit surfaces the lock-in while you still have time to renegotiate it."),
               ("Price the Exit", "Runout claims priced at the PBM's discretion can make leaving expensive enough to deter it. The third pass prices the exit, so 'you're free to leave' is tested against what leaving actually costs."),
               ("This Quarter's Action Plan", "Run the three passes, document the lock-in terms, and renegotiate data ownership and runout pricing at renewal. Leverage you can only use at exit has to be written in long before you exit.")],
        mechanic="termination leverage", pillar="PBM Contract Insights",
        alt="Termination clause audit worksheet with five exit terms and an exit-cost timeline",
        pdf=up("week_35_thursday_termination_clause_audit.pdf"),
        related="member-transition-audit, rfp-scoring-audit, definition-variance-audit",
        second_name="Member Transition Audit", second_url=up("week_33_thursday_member_transition_audit.pdf"),
        second_blurb="Clean exit and clean transition are two sides of the same move. The Member Transition Audit checks whether the continuity-of-care protections execute when you leave, so the exit leverage you secured here doesn't harm members on the way out.",
        fn_title="Can You Actually Leave Your PBM? Read These Five Terms.",
        fn_blurb="The worksheet audits the exit. This Field Note decodes the termination clause: how data ownership and runout pricing turn 'you can terminate' into 'good luck leaving clean.'"),

    dict(
        slug="definition-variance-audit", Title="Definition Variance Audit", kind="worksheet",
        eyebrow="TIER 2 · CONTRACT DEFINITIONS · VARIANCE AUDIT",
        headline="Same Words. Different Meanings.",
        headline_emphasis="Across Renewal Cycles, the Definitions Quietly Shrink.",
        bullets=["Three audit passes across your contract's definitions",
                 "Compare definitions across past contract versions",
                 "Where 'generic,' 'brand,' and 'specialty' quietly drifted",
                 "The silent drift that shrinks every guarantee"],
        cards=[("Pull Past Versions", "The first pass gathers your current and prior contract versions. Definition drift is invisible in any single contract; it only shows up when you line up 'generic,' 'brand,' 'specialty,' and 'rebate' across versions."),
               ("Track the Drift", "Across renewal cycles the definitions quietly shrink. A drug reclassified from 'generic' to 'specialty' moves it into the bucket with the weakest guarantee, with no change to the headline discount."),
               ("Connect Definitions to Dollars", "Every guarantee is only as strong as the definition under it. The third pass connects each drifted definition to the guarantee it weakens, so the cost of a wording change becomes visible."),
               ("This Quarter's Action Plan", "Run the three passes, document every definition that drifted, and lock the definitions at renewal. The most expensive edits to a PBM contract are the ones to the words, not the numbers.")],
        mechanic="definition drift", pillar="PBM Contract Insights",
        alt="Definition variance audit worksheet comparing contract definitions across renewal versions",
        pdf=up("week_36_thursday_definition_variance_audit.pdf"),
        related="ger-audit, termination-clause-audit, quarterly-reporting",
        second_name="Generic Effective Rate Audit Worksheet", second_url=up("week_28_thursday_ger_audit_worksheet.pdf"),
        second_blurb="Definition drift and the GER guarantee are directly linked: the generic definition decides which claims the guarantee even covers. The GER Audit Worksheet reconciles the guaranteed rate against actual performance once you've caught the definition shrinking.",
        fn_title="The Most Expensive Edits to Your PBM Contract Are the Words",
        fn_blurb="The worksheet tracks the drift. This Field Note shows how a quiet wording change across renewals, one drug reclassified, one definition narrowed, hollows out a guarantee while the discount looks unchanged."),

    dict(
        slug="pre-meeting-renewal-checklist", Title="First Renewal Meeting Pre-Meeting Checklist", kind="checklist",
        eyebrow="TIER 2 · FIRST RENEWAL MEETING · PRE-MEETING CHECKLIST",
        headline="Five Items to Bring to the First PBM Renewal Meeting.",
        headline_emphasis="The First Meeting Sets the Frame.",
        bullets=["Five documents to bring to the first renewal meeting",
                 "One internal priority list, agreed before you walk in",
                 "One counter-narrative to the PBM's proposal",
                 "Set the frame before the PBM does"],
        cards=[("Bring Five Documents", "Five documents change the first renewal meeting: your independent claims analysis, your audit findings, your priority list, your benchmark data, and your draft term sheet. Walk in with all five or react to the PBM's."),
               ("Agree the Priorities First", "The internal priority list, agreed across HR, finance, and the broker before the meeting, prevents the PBM from dividing the room. One voice, one set of priorities, decided in advance."),
               ("Bring the Counter-Narrative", "The PBM arrives with a proposal and a story. The checklist makes sure you arrive with your own: the documented findings that reframe the conversation from their renewal to your terms."),
               ("This Quarter's Action Plan", "Assemble the five documents, hold the internal alignment meeting, and pre-circulate the counter-narrative to your committee. The first meeting sets the frame for every meeting after it.")],
        mechanic="renewal meeting prep", pillar="Self-Funded Employer Guidance",
        alt="First renewal meeting pre-meeting checklist with five documents and a counter-narrative",
        pdf=up("week_37_thursday_pre_meeting_renewal_checklist.pdf"),
        related="h1-renewal-readiness, pbr-framework, midyear-claims-red-flag",
        second_name="H1 Renewal Readiness Scorecard", second_url=up("week_24_h1_renewal_readiness_scorecard.pdf"),
        second_blurb="The Pre-Meeting Checklist gets you into the room prepared; the H1 Renewal Readiness Scorecard is what fills the folder. Score your leverage on the five metrics the PBM models, then bring that score as your counter-narrative.",
        fn_title="How to Walk Into a PBM Renewal Meeting in Control",
        fn_blurb="The checklist assembles the five documents. This Field Note covers the meeting itself: how the first renewal conversation sets the frame, and how a prepared plan sponsor keeps control of it."),
]

def build_row(d):
    return {
        "slug": d["slug"],
        "Title": d["Title"],
        "eyebrow": d["eyebrow"],
        "headline": d["headline"],
        "headline_emphasis": d["headline_emphasis"],
        "subtitle": SUBTITLE.format(kind=d["kind"]),
        "bullet_1": d["bullets"][0],
        "bullet_2": d["bullets"][1],
        "bullet_3": d["bullets"][2],
        "bullet_4": d["bullets"][3],
        "valueprop_card_1_title": d["cards"][0][0],
        "valueprop_card_1_body": d["cards"][0][1],
        "valueprop_card_2_title": d["cards"][1][0],
        "valueprop_card_2_body": d["cards"][1][1],
        "valueprop_card_3_title": d["cards"][2][0],
        "valueprop_card_3_body": d["cards"][2][1],
        "valueprop_card_4_title": d["cards"][3][0],
        "valueprop_card_4_body": d["cards"][3][1],
        "pdf_filename_display": d["Title"],
        "seo_title": f"{d['Title']} - Free Download - Prescription Benefit Solutions",
        "seo_description": seo_desc(d["kind"], d["headline_emphasis"]),
        "related_toolkit_slugs": d["related"],
        "image_alt_text": d["alt"],
        "pdf_url": d["pdf"],
        "tier": "2",
        "mechanic_phrase": d["mechanic"],
        "is_featured": "FALSE",
        "is_archived": "FALSE",
        "second_toolkit_name": d["second_name"],
        "second_toolkit_pdf_url": d["second_url"],
        "second_toolkit_blurb": d["second_blurb"],
        # Option A: evergreen Library default until the dedicated Field Note ships.
        # Per-row dedicated copy is preserved in d["fn_title"] / d["fn_blurb"] for the swap.
        "field_note_title": LIBRARY_TITLE,
        "field_note_blurb": LIBRARY_BLURB,
        "field_note_url": LIBRARY_URL,
    }

def main():
    out = os.path.join(os.path.dirname(__file__), "tier2_toolkits_for_wix_import.csv")
    with open(out, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=COLUMNS, quoting=csv.QUOTE_ALL)
        w.writeheader()
        for d in ROWS:
            w.writerow(build_row(d))
    print(f"Wrote {len(ROWS)} Tier 2 rows to {out}")

if __name__ == "__main__":
    main()
